name: Build Tweak
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
      - name: Build Package
        run: |
          export THEOS=$HOME/theos
          make package FINALPACKAGE=1
      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: JckaakApp-deb
          path: packages/*.deb
